baseURL = "https://selfhostedsystems.com/"
languageCode = "en-gb"
title = "Self Hosted Systems"
theme = "PaperMod"

[params]
  defaultTheme = "auto"   # auto | dark | light
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowToc = true

