[[main]]
  name = "Docs"
  url = "/docs/"
  weight = 10

[[main]]
  name = "Operations"
  url = "/docs/operations/"
  weight = 20

[[main]]
  name = "Architecture"
  url = "/docs/architecture/"
  weight = 30

[[main]]
  name = "Scaling"
  url = "/docs/scaling/"
  weight = 40
